### ISSUE TITLE
Add new chain faucet (edeXa)

### ISSUE THREAD

**Issue by ranjith-edx** [Web3ID/awesome-list-testnet-faucets#128]
is it possible to add our chain faucet to the list here 

https://faucet.edexa.com/

**Comment by shubham-edx** [comment]
@abraham-yusuf Can you please look into it?

**Comment by abraham-yusuf** [comment]
> @abraham-yusuf Can you please look into it?

sure

**Comment by abraham-yusuf** [comment]
https://github.com/Web3ID/awesome-list-testnet-faucets/commit/46770b272e1d5da2e8b88d4d27c6aa91b34f9848
